# concatenate string  

In [5]:
# use sum operator to connect strings
print('hello' + ' ' + 'world' + '!')

hello world!


# subsetting list

In [6]:
lst = [1, 2, 3, 4, 5, 6]
# index of the 1st element is 0
print(lst[0])
# index of the last element is -1
print(lst[-1])

1
6


# extend list

In [8]:
# append new elements to a list
print(lst + [7, 8, 9])

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# delete list elements

In [11]:
print(lst)
del(lst[-1])
print(lst)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5]


# in-place VS not-in-place && python list VS numpy array

In [34]:
# '+' is not-in-place operation in python list 
lst1 = [1, 2, 3]
lst3 = lst1
print(lst1, lst3)

lst2 = [4, 5, 6]
lst1 = lst1 + lst2
print(lst1, lst3)

[1, 2, 3] [1, 2, 3]
[1, 2, 3, 4, 5, 6] [1, 2, 3]


In [35]:
# '+=' is in-place operation in python list
lst1 = [1, 2, 3]
lst3 = lst1
print(lst1, lst3)

lst2 = [4, 5, 6]
lst1 += lst2
print(lst1, lst3)

[1, 2, 3] [1, 2, 3]
[1, 2, 3, 4, 5, 6] [1, 2, 3, 4, 5, 6]


In [43]:
# slicing is not-in-place operation in python list
lst1 = [1, 2, 3]
lst2 = lst1[1:]
print(lst1, lst2)
lst1[1] = 0
print(lst1, lst2)

lst3 = [1, 2, 3]
lst4 = lst3[1:]
print(lst3, lst4)
lst4[0] = 0
print(lst3, lst4)

[1, 2, 3] [2, 3]
[1, 0, 3] [2, 3]
[1, 2, 3] [2, 3]
[1, 2, 3] [0, 3]


In [ ]:
import numpy as np

In [31]:
# '+' is not-in-place operation in numpy array
array1 = np.array([1,2,3])
array3 = array1
print(array1, array3)

array2 = np.array([1, 1, 1])
array1 = array1 + array2
print(array1, array3)

[1 2 3] [1 2 3]
[2 3 4] [1 2 3]


In [36]:
# '+=' is in-place operation in numpy array
array1 = np.array([1,2,3])
array3 = array1
print(array1, array3)

array2 = np.array([1, 1, 1])
array1 += array2
print(array1, array3)

[1 2 3] [1 2 3]
[2 3 4] [2 3 4]


In [42]:
# slicing is in-place-operation in numpy array
array1 = np.array([1,2,3])
array2 = array1[1:]
print(array1, array2)

array1[1] = 0
print(array1, array2)

array3 = np.array([1,2,3])
array4 = array3[1:]
print(array3, array4)

array4[0] = 0
print(array3, array4)

[1 2 3] [2 3]
[1 0 3] [0 3]
[1 2 3] [2 3]
[1 0 3] [0 3]


# sorted function

In [49]:
help(sorted)
lst = [1, 0, 3, 1.3, 8]
print(lst)
lst = sorted(lst, reverse=True)
print(lst)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

[1, 0, 3, 1.3, 8]
[8, 3, 1.3, 1, 0]


# methods

In [55]:
string = 'hello'
string = string.upper()
print(string)
print(string.count('L'))

HELLO
2


In [63]:
lst = [1, 2, 3, 3, 4, 5]
print(lst.index(2))
print(lst.count(3))
lst.append(9)
print(lst)
lst.reverse()
print(lst)

1
2
[1, 2, 3, 3, 4, 5, 9]
[9, 5, 4, 3, 3, 2, 1]
